import { useEffect, useState } from 'react';
import { Card, CardBody, Text, Container, Box, Heading } from "@chakra-ui/react";

function TextBox({ bgColor, text, onClick }) {

    return (
        <Card mt="10px" mb="10px" size="lg" bg={bgColor} onClick={onClick} cursor="pointer">
            <CardBody>
                <Text>{text}</Text>
            </CardBody>
        </Card>
    )
}

function TextBoxGroup({ textArray }) {
    const [bgColors, setBgColors] = useState(["white", "white", "white"]);

    function changeBgColors() {
        let newBgColors = textArray.map((textObj) => {
            return (textObj.fact ? "green.100" : "red.100");
        });
        console.log(newBgColors);
        setBgColors(newBgColors);
    }
    
    const textBoxes = textArray.map((textObj, index) => 
        <TextBox bgColor={bgColors[index]} text={textObj.text} onClick={changeBgColors}></TextBox>);
    return (
        <Container>
            {textBoxes}
        </Container>
    )
}

export default function FunFact() {
    
    const [texts, setTexts] = useState([{fact: null, text: "Loading..."}, {fact: null, text: "Loading..."}, {fact: null, text: "Loading..."}]);
    
    useEffect(() => {

            async function getFact() {
                try {
                    const response = await fetch("https://thienan-api.onrender.com/facts/getOneRandom");
                    const jsonData = await response.json();
                    
                    // for some reason, the response is returned in an array so we have to 
                    // index into the array to get the object
                    return [{fact: true, text: jsonData[0].content}];
                }
                catch (error) {
                    console.log(error);
                    return [{fact: true, text: "Thienan can only identify three states on the USA map."}];
                }
            }

            async function getTwoLies() {
                try {
                    const response = await fetch("https://thienan-api.onrender.com/lies/getTwoLies");
                    const jsonData = await response.json();
                    return [{fact: false, text: jsonData.fact1}, {fact: false, text: jsonData.fact2}];
                }
                catch (error) {
                    console.log(error);
                    return [{fact: false, text: "Thienan once wore the same shirt everyday for a month"}, 
                            {fact: false, text: "Thienan can do a perfect cartwheel"}];
                }
            }

            getFact().then((factArray) => {
                getTwoLies().then((liesArray) => {

                    // lies generated by ChatGPT don't have periods, so we have to append a period
                    // else the fact is always the sentence ending with a period.

                    liesArray[0].text += ".";
                    liesArray[1].text += ".";
                    const contentArray = factArray.concat(liesArray);
                    console.log(contentArray)
                    
                    const shuffledContents = contentArray
                        .map(value => ({ value, sort: Math.random() }))
                        .sort((a, b) => a.sort - b.sort)
                        .map(({ value }) => value)
                    
                    setTexts(shuffledContents);
                })
            })
    }, []);

    // const texts = [{fact: true, text: "fact"}, {fact: false, text: "lie"}, {fact: false, text: "lie"}];
    return (
        <Box>
            <Heading size="md" textAlign="center">Which fact is true about Thienan?</Heading>
            <Text textAlign="center" mb="20px">Click what you think is the fact. The fact will light up green!</Text>
            <TextBoxGroup textArray={texts}></TextBoxGroup>
            <Text textAlign="center" mb="20px" mt="20px">Loading time is like a minute for the first
            render so sit tight. 5-10 seconds for renders after that.</Text>
        </Box>
    )
}